[tools] add tool to compute steering data (#184)

diff --git a/tests/tools/test-pskc b/tests/tools/test-pskc
--- a/tests/tools/test-pskc
+++ b/tests/tools/test-pskc
@@ -1,5 +1,6 @@
+#!/bin/bash
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2018, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -25,14 +26,23 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
+# Test generating steering data.
+#
+set -e
 
-include $(abs_top_nlbuild_autotools_dir)/automake/pre.am
+readonly COMPUTER="${top_builddir}/tools/pskc"
 
-SUBDIRS         = \
-    mdns          \
-    meshcop       \
-    tools         \
-    unit          \
-    $(NULL)
+die()
+{
+  exit_message="$@"
+  echo " *** ERROR: " "$@"
+  exit 1
+}
 
-include $(abs_top_nlbuild_autotools_dir)/automake/post.am
+main()
+{
+    "${COMPUTER}" | grep -q 'SYNTAX' || die "No help information found!"
+    [[ "$("${COMPUTER}"  654321 1122334455667788 OpenThread)" = 07708bf664c00858c19269cf10261e5b ]] || die "Wrong PSKc!"
+}
+
+main "$@"
diff --git a/tests/tools/test-steering-data b/tests/tools/test-steering-data
--- a/tests/tools/test-steering-data
+++ b/tests/tools/test-steering-data
@@ -1,5 +1,6 @@
+#!/bin/bash
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2018, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -25,14 +26,31 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
+# Test generating steering data.
+#
+set -e
+set -x
 
-include $(abs_top_nlbuild_autotools_dir)/automake/pre.am
+readonly COMPUTER="${top_builddir}/tools/steering-data"
 
-SUBDIRS         = \
-    mdns          \
-    meshcop       \
-    tools         \
-    unit          \
-    $(NULL)
+die()
+{
+  exit_message="$@"
+  echo " *** ERROR: " "$@"
+  exit 1
+}
 
-include $(abs_top_nlbuild_autotools_dir)/automake/post.am
+main()
+{
+    "${COMPUTER}" | grep -q 'SYNTAX' || die "No help information found!"
+    ! "${COMPUTER}" 32 18b4300000000002 || die "Validation error expected!"
+    ! "${COMPUTER}" 0 18b4300000000002 || die "Validation error expected!"
+    ! "${COMPUTER}" -1 18b4300000000002 || die "Validation error expected!"
+    [[ "$("${COMPUTER}" 1)" = 00 ]] || die "Wrong steering data!"
+    [[ "$("${COMPUTER}" 18b4300000000002)" = 00000000000000000000000000000012 ]] || die "Wrong steering data!"
+    [[ "$("${COMPUTER}" 16 18b4300000000002)" = 00000000000000000000000000000012 ]] || die "Wrong steering data!"
+    [[ "$("${COMPUTER}" 18b4300000000002 18b4300000000003)" = 00000000000008002000000000000012 ]] || die "Wrong steering data!"
+    [[ "$("${COMPUTER}" 16 18b4300000000002 18b4300000000003)" = 00000000000008002000000000000012 ]] || die "Wrong steering data!"
+}
+
+main "$@"
