Drop -e from echo to make code more consistent
Co-authored-by: Jonathan Hui <jonhui@google.com>

diff --git a/etc/docker/border-router/setup-host b/etc/docker/border-router/setup-host
--- a/etc/docker/border-router/setup-host
+++ b/etc/docker/border-router/setup-host
@@ -40,7 +40,7 @@ readonly SYSCTL_IP_FORWARD_FILE
 
 die()
 {
-    echo -e "${*}" 1>&2
+    echo >&2 "ERROR: $*"
     exit 1
 }
 
