[travis] make travis scripts locally runnable

diff --git a/.travis/check-scripts b/.travis/check-scripts
--- a/.travis/check-scripts
+++ b/.travis/check-scripts
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2018, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -30,40 +30,45 @@
 set -e
 set -x
 
-TOOLS_HOME=$HOME/.cache/tools
+main() {
+    RELEASE=1 ./script/bootstrap
+    ./script/bootstrap
+    NAT64=1 ./script/setup
+    SOCAT_OUTPUT=/tmp/ot-socat
 
-die() {
-	echo " *** ERROR: " $*
-	exit 1
+    socat -d -d pty,raw,echo=0 pty,raw,echo=0 > /dev/null 2> $SOCAT_OUTPUT &
+    while true; do
+        if test $(head -n2 $SOCAT_OUTPUT | wc -l) = 2; then
+            DEVICE_PTY=$(head -n1 $SOCAT_OUTPUT | grep -o '/dev/.\+')
+            WPANTUND_PTY=$(head -n2 $SOCAT_OUTPUT | tail -n1 | grep -o '/dev/.\+')
+            break
+        fi
+        echo 'Waiting for socat ready...'
+        sleep 1
+    done
+    echo 'DEVICE_PTY' $DEVICE_PTY
+    echo 'WPANTUND_PTY' $WPANTUND_PTY
+    # default configuration for Thread device is /dev/ttyUSB0
+    sudo ln -s $WPANTUND_PTY /dev/ttyUSB0 || die 'Failed to create ttyUSB0!'
+
+    ot-ncp-ftd 1 > $DEVICE_PTY < $DEVICE_PTY &
+    ./script/console & SERVICES_PID=$!
+    sudo service tayga start
+    echo 'Waiting for services to be ready...'
+    sleep 10
+    netstat -an | grep 49191 || die 'Service otbr-agent not ready!'
+    netstat -an | grep 80 || die 'Service otbr-web not ready!'
+    pidof tayga || die 'tayga not running'
+    kill $SERVICES_PID || die 'Failed to stop services!'
+    sudo killall otbr-web || true
+    sudo killall otbr-agent || true
+    sudo killall wpantund || true
+    sudo service tayga stop || true
+    killall ot-ncp-ftd || die 'Failed to end OpenThread!'
+    killall socat || die 'Failed to end socat!'
+    jobs
+    echo 'Waiting for services to end...'
+    wait
 }
 
-case $BUILD_TARGET in
-android-check)
-    (cd .. && "${TRAVIS_BUILD_DIR}/.travis/check-android-build")
-    ;;
-
-pretty-check)
-    export PATH=$TOOLS_HOME/usr/bin:$PATH
-    ./bootstrap && ./configure && make pretty-check || die
-    ;;
-
-posix-check)
-    CPPFLAGS="$CFLAGS -I$TOOLS_HOME/usr/include" LDFLAGS="$LDFLAGS -L$TOOLS_HOME/usr/lib" .travis/check-posix
-    ;;
-
-scan-build)
-    .travis/check-scan-build
-    ;;
-
-script-check)
-    .travis/check-scripts
-    ;;
-
-raspbian-gcc)
-    IMAGE_FILE=$TOOLS_HOME/images/$IMAGE_NAME.img .travis/check-raspbian
-    ;;
-
-*)
-    die
-    ;;
-esac
+main "$@"
