Add NetworkManager to make WiFi configuration easier.

diff --git a/script/_dhcpv6_pd b/script/_dhcpv6_pd
--- a/script/_dhcpv6_pd
+++ b/script/_dhcpv6_pd
@@ -33,7 +33,13 @@
 # Currently solution was verified only on raspbian and ubuntu.
 #
 
-WAN_INTERFACE="eth0"
+if [ $PLATFORM = "ubuntu" ]; then
+    WAN_INTERFACE="enp0s3"
+else
+    WAN_INTERFACE="eth0"
+fi
+
+WLAN_INTERFACE="wlan0"
 
 WPANTUND_INTERFACE="wpan0"
 WPANTUND_ENV="/etc/default/wpantund"
@@ -44,7 +50,7 @@ DHCPCD_CONF_BACKUP="$DHCPCD_CONF.orig"
 DHCPCD_RELOADER="/usr/sbin/dhcpcd_reloader"
 DHCPCD_RELOADER_SERVICE="/etc/systemd/system/dhcpcd_reloader.service"
 
-without DHCPV6_PD || test $PLATFORM = raspbian || die "DHCPv6-PD is not tested under $PLATFORM."
+without DHCPV6_PD || test $PLATFORM = raspbian || test $PLATFORM = ubuntu || die "DHCPv6-PD is not tested under $PLATFORM."
 
 create_dhcpcd_conf_with_dhcpv6_pd()
 {
@@ -64,9 +70,6 @@ hostname
 # Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
 duid
 
-# Persist interface configuration when dhcpcd exits.
-persistent
-
 # Rapid commit support.
 # Safe to enable by default because it requires the equivalent option set
 # on the server to actually work.
@@ -85,22 +88,33 @@ option ntp_servers
 require dhcp_server_identifier
 
 # Generate Stable Private IPv6 Addresses instead of hardware based ones
-slaac private
+slaac hwaddr 
 
 # A hook script is provided to lookup the hostname if not set by the DHCP
 # server, but it should not be run by default.
 nohook lookup-hostname
+nohook wpa_supplicant
+
+denyinterfaces nat*
 
 noipv6rs
 
 interface $WPANTUND_INTERFACE
+iaid 0
 nodhcp
 nodhcp6
 
 interface $WAN_INTERFACE
+iaid 1
 ipv6rs
-ia_na 1
-ia_pd 2/::/63 $WPANTUND_INTERFACE/1
+ia_na 2 
+ia_pd 3/::/63 $WPANTUND_INTERFACE/1
+
+interface $WLAN_INTERFACE 
+iaid 4
+ipv6rs
+ia_na 5
+ia_pd 6/::/63 $WPANTUND_INTERFACE/1
 
 EOF
 }
@@ -116,7 +130,7 @@ NAME="dhcpcd_reloader"
 echo \${PID} > /tmp/\${NAME}.pid
 
 if [ -z \${IFACE} ]; then
-        IFACE="$WPANTUND_INTERFACE"
+    IFACE="$WPANTUND_INTERFACE"
 fi
 
 WPANTUND_IFACE="com.nestlabs.WPANTunnelDriver"
@@ -126,18 +140,29 @@ WATCH1="type='signal', interface=\${WPANTUND_IFACE}, path=\${WPANTUND_NCP_STATE_
 
 reload_dhcpcd_daemon()
 {
-        systemctl force-reload dhcpcd
-        systemctl reload-daemon
-        logger -t "\${NAME}[\${PID}]" "Reload: dhcpcd daemon"
+    if systemctl is-active NetworkManager; then
+        logger -t "\${NAME}[\${PID}]" "NetworkManager: active"
+
+        for interface in \$(pgrep dhcpcd -a -x | rev | cut -d" " -f1 | rev); do
+            logger -t "\${NAME}[\${PID}]" "dhcpcd: rebind \${interface}"
+            /sbin/dhcpcd -6 -n \${interface}
+        done
+    fi
+
+    if systemctl is-active dhcpcd; then
+        logger -t "\${NAME}[\${PID}]" "dhcpcd: reload daemon"
+        sudo systemctl reload-daemon
+        sudo systemctl force-reload dhcpcd
+    fi
 }
 
 process_output()
 {
-        while read -r line; do
-                if echo \${line} | grep -q "associated"; then
-                        reload_dhcpcd_daemon
-                fi
-        done
+    while read -r line; do
+        if echo \${line} | grep -q "associated"; then
+            reload_dhcpcd_daemon
+        fi
+    done
 }
 
 dbus-monitor --system "\${WATCH1}" | process_output
@@ -156,7 +181,7 @@ ConditionPathExists=/usr/sbin/dhcpcd_reloader
 [Service]
 ExecStart=/bin/sh /usr/sbin/dhcpcd_reloader
 PIDFile=/tmp/dhcpcd_resolver.pid
-KillType=process
+KillMode=control-group
 
 [Install]
 WantedBy=multi-user.target
@@ -183,7 +208,15 @@ dhcpv6_pd_install()
     if have systemctl; then
         create_dhcpcd_reloader_service
 
-        sudo systemctl restart dhcpcd || die 'Unable to restart dhcpcd!'
+        sudo systemctl daemon-reload
+
+        if systemctl is-active NetworkManager; then
+            sudo systemctl restart NetworkManager || die "Unable to restart NetworkManager!"
+        fi
+
+        if systemctl is-active dhcpcd; then
+            sudo systemctl restart dhcpcd || die 'Unable to restart dhcpcd!'
+        fi
 
         sudo systemctl start dhcpcd_reloader.service || die 'Unable to start dhcpcd_reloader!'
         sudo systemctl enable dhcpcd_reloader.service || die 'Unable to enable dhcpcd_reloader!'
@@ -200,14 +233,24 @@ dhcpv6_pd_uninstall()
 
         sudo rm -rf $DHCPCD_RELOADER_SERVICE || true
     fi
-    
-    sudo rm -rf $DHCPCD_RELOADER || true
-    sudo rm -rf $WPANTUND_ENV || true
+
+    sudo rm ${DHCPCD_RELOADER} || true
+    sudo rm ${WPANTUND_ENV} || true
 
     # Restore backup of the default configuration of dhcpcd
-    sudo mv $DHCPCD_CONF_BACKUP $DHCPCD_CONF || true
+    sudo mv ${DHCPCD_CONF_BACKUP} ${DHCPCD_CONF} || true
 
+    # Restart dhcpcd or NetworkManager
     if have systemctl; then
-        sudo systemctl restart dhcpcd.service || true
+        sudo systemctl daemon-reload
+
+        if systemctl is-active NetworkManager; then
+            sudo systemctl restart NetworkManager || true
+        fi
+
+        if systemctl is-active dhcpcd; then
+            sudo systemctl restart dhcpcd.service || true
+        fi
     fi
 }
+
