[docker] add docker support (#183)

diff --git a/script/_dns64 b/script/_dns64
--- a/script/_dns64
+++ b/script/_dns64
@@ -66,10 +66,13 @@ dns64_install()
     with NAT64 && with DNS64 || return 0
 
     test -f $BIND_CONF_OPTIONS || die 'Cannot find bind9 configuration file!'
-    sudo sed -i '/^};/i\\tallow-recursion { any; };' $BIND_CONF_OPTIONS
+    sudo sed -i '/^};/i\\tlisten-on-v6 { any; };' $BIND_CONF_OPTIONS
+    sudo sed -i '/^};/i\\tallow-query { any; };' $BIND_CONF_OPTIONS
+    sudo sed -i '/^};/i\\tforwarders { 8.8.8.8; 8.8.8.4; };' $BIND_CONF_OPTIONS
+    sudo sed -i '/^};/i\\tforward only;' $BIND_CONF_OPTIONS
     sudo sed -i '/^};/i\\t'"$DNS64_CONF" $BIND_CONF_OPTIONS
 
-    sudo sh -c "echo \"nameserver $DNS64_NAMESERVER_ADDR\" >> $RESOLV_CONF_HEAD"
+    [ -f /.dockerenv ] || sudo sh -c "echo \"nameserver $DNS64_NAMESERVER_ADDR\" >> $RESOLV_CONF_HEAD"
 
     if have systemctl; then
         sudo systemctl enable bind9 || true
@@ -77,12 +80,13 @@ dns64_install()
         sudo systemctl start bind9 || die 'Failed to start bind9!'
     fi
 
-    dns64_update_resolvconf
+    [ -f /.dockerenv ] ||  dns64_update_resolvconf
 }
 
 dns64_uninstall()
 {
     with NAT64 && with DNS64 || return 0
+    [ ! -f /.dockerenv ] || return 0
 
     dns64_stop
     sudo sed -i '/^\tallow-recursion/d' $BIND_CONF_OPTIONS
@@ -104,6 +108,8 @@ dns64_start()
 
     if have systemctl; then
         sudo systemctl start bind9 || die 'Failed to start bind9!'
+    elif which service; then
+        sudo service bind9 start || die 'Failed to start bind9!'
     fi
 }
 
@@ -113,5 +119,7 @@ dns64_stop()
 
     if have systemctl; then
         sudo systemctl stop bind9 || true
+    elif which service; then
+        sudo service bind9 stop || true
     fi
 }
diff --git a/script/_nat64 b/script/_nat64
--- a/script/_nat64
+++ b/script/_nat64
@@ -38,7 +38,7 @@ WLAN_IFNAMES=eth0
 
 # Currently solution was verified only on raspbian and ubuntu.
 #
-without NAT64 || test $PLATFORM = ubuntu || test $PLATFORM = raspbian || die "nat64 is not tested under $PLATFORM."
+#without NAT64 || test $PLATFORM = ubuntu || test $PLATFORM = raspbian || die "nat64 is not tested under $PLATFORM."
 
 nat64_install()
 {
@@ -147,7 +147,9 @@ nat64_start()
 {
     with NAT64 || return 0
 
-    if have systemctl; then
+    if [ -f /.dockerenv ]; then
+        service tayga start || die 'Failed to start tayga'
+    elif have systemctl; then
         sudo systemctl start tayga || die 'Failed to start tayga!'
         sudo systemctl start otbr-nat44 || die 'Failed to start NAT44!'
     fi
@@ -157,7 +159,9 @@ nat64_stop()
 {
     with NAT64 || return 0
 
-    if have systemctl; then
+    if [ -f /.dockerenv ]; then
+        service tayga stop || true
+    elif have systemctl; then
         sudo systemctl stop tayga || true
         sudo systemctl stop otbr-nat44 || true
     fi
