Improve DNS64 script.

diff --git a/script/_dns64 b/script/_dns64
--- a/script/_dns64
+++ b/script/_dns64
@@ -31,11 +31,29 @@
 #
 
 BIND_CONF_OPTIONS=/etc/bind/named.conf.options
-RESOLV_CONF=/etc/resolv.conf
 NAT64_PREFIX=64:ff9b::/96
 
 DNS64_NAMESERVER_ADDR=127.0.0.1
 DNS64_CONF="dns64 `echo $NAT64_PREFIX | tr \"/\" \"\/\"` { clients { any; }; recursive-only yes; };"
+
+# Currently solution was verified only on raspbian and ubuntu.
+#
+without NAT64 || test $PLATFORM = ubuntu || test $PLATFORM = raspbian || die "dns64 is not tested under $PLATFORM."
+
+if [ $PLATFORM = raspbian ]; then
+    RESOLV_CONF_HEAD=/etc/resolv.conf.head
+elif [ $PLATFORM = ubuntu ]; then
+    RESOLV_CONF_HEAD=/etc/resolvconf/resolv.conf.d/head
+fi
+
+dns64_update_resolvconf()
+{
+    if [ $PLATFORM = ubuntu ]; then
+        sudo resolvconf -u || true
+    elif [ $PLATFORM = raspbian ]; then
+        sudo systemctl restart dhcpcd || true
+    fi
+}
 
 dns64_install()
 {
@@ -44,26 +62,43 @@ dns64_install()
     test -f $BIND_CONF_OPTIONS || die 'Cannot find bind9 configuration file!'
     sudo sed -i '/^};/i\\tallow-recursion { any; };' $BIND_CONF_OPTIONS
     sudo sed -i '/^};/i\\t'"$DNS64_CONF" $BIND_CONF_OPTIONS
+
+    sudo sh -c "echo \"nameserver $DNS64_NAMESERVER_ADDR\" >> $RESOLV_CONF_HEAD"
+
+    if have systemctl; then
+        sudo systemctl enable bind9 || true
+        sudo systemctl is-enabled bind9 || die 'Failed to enable bind9!'
+        sudo systemctl start bind9 || die 'Failed to start bind9!'
+    fi
+
+    dns64_update_resolvconf
 }
 
 dns64_uninstall()
 {
     with NAT64 && with DNS64 || return 0
 
-    dns64_stop    
+    dns64_stop
     sudo sed -i '/^\tallow-recursion/d' $BIND_CONF_OPTIONS
     sudo sed -i '/^\tdns64/d' $BIND_CONF_OPTIONS
+
+    sudo sed -i '/^nameserver '$DNS64_NAMESERVER_ADDR'/d' $RESOLV_CONF_HEAD || true
+
+    dns64_update_resolvconf
+
+    if have systemctl; then
+        sudo systemctl stop bind9 || true
+        sudo systemctl disable bind9 || true
+    fi
 }
 
 dns64_start()
 {
     with NAT64 && with DNS64 || return 0
 
-    if have systemctl; then    
+    if have systemctl; then
         sudo systemctl start bind9 || die 'Failed to start bind9!'
     fi
-
-    sudo sed -i '1a nameserver '$DNS64_NAMESERVER_ADDR $RESOLV_CONF
 }
 
 dns64_stop()
@@ -73,6 +108,4 @@ dns64_stop()
     if have systemctl; then
         sudo systemctl stop bind9 || true
     fi
-
-    sudo sed -i '/^nameserver\s'$DNS64_NAMESERVER_ADDR'/d' $RESOLV_CONF
 }
