[docker] fix on ubuntu 20.04 (#409)
* avoid configuring tzdata

* support new name of bind9

diff --git a/script/_dns64 b/script/_dns64
--- a/script/_dns64
+++ b/script/_dns64
@@ -61,6 +61,11 @@ dns64_update_resolvconf()
     fi
 }
 
+_detect_service_name()
+{
+    dpkg -L bind9 | grep /etc/init.d/ | cut -d/ -f4
+}
+
 dns64_install()
 {
     with NAT64 && with DNS64 || return 0
@@ -75,12 +80,14 @@ dns64_install()
     sudo sed -i '/^};/i\\t'"$DNS64_CONF" $BIND_CONF_OPTIONS
     sudo sed -i '1s/^/acl thread {\n\tfe80::\/16;\n\tfc00::\/7;\n\t127.0.0.1;\n};\n\n/' $BIND_CONF_OPTIONS
 
+    service_name="$(_detect_service_name)"
+
     [ -f /.dockerenv ] || sudo sh -c "echo \"nameserver $DNS64_NAMESERVER_ADDR\" >> $RESOLV_CONF_HEAD"
 
     if have systemctl; then
-        sudo systemctl enable bind9 || true
-        sudo systemctl is-enabled bind9 || die 'Failed to enable bind9!'
-        sudo systemctl start bind9 || die 'Failed to start bind9!'
+        sudo systemctl enable "${service_name}" || true
+        sudo systemctl is-enabled "${service_name}" || die 'Failed to enable bind9!'
+        sudo systemctl start "${service_name}" || die 'Failed to start bind9!'
     fi
 
     [ -f /.dockerenv ] ||  dns64_update_resolvconf
@@ -89,6 +96,8 @@ dns64_install()
 dns64_uninstall()
 {
     with NAT64 && with DNS64 || return 0
+
+    service_name="$(_detect_service_name)"
 
     dns64_stop
     sudo sed -i '/^\tlisten-on-v6/d' $BIND_CONF_OPTIONS
@@ -104,8 +113,8 @@ dns64_uninstall()
     [ -f /.dockerenv ] ||  dns64_update_resolvconf
 
     if have systemctl; then
-        sudo systemctl stop bind9 || true
-        sudo systemctl disable bind9 || true
+        sudo systemctl stop "${service_name}" || true
+        sudo systemctl disable "${service_name}" || true
     fi
 }
 
@@ -113,10 +122,12 @@ dns64_start()
 {
     with NAT64 && with DNS64 || return 0
 
+    service_name="$(_detect_service_name)"
+
     if have systemctl; then
-        sudo systemctl start bind9 || die 'Failed to start bind9!'
+        sudo systemctl start "${service_name}" || die 'Failed to start bind9!'
     elif which service; then
-        sudo service bind9 start || die 'Failed to start bind9!'
+        sudo service "${service_name}" start || die 'Failed to start bind9!'
     fi
 }
 
@@ -124,9 +135,11 @@ dns64_stop()
 {
     with NAT64 && with DNS64 || return 0
 
+    service_name="$(_detect_service_name)"
+
     if have systemctl; then
-        sudo systemctl stop bind9 || true
+        sudo systemctl stop "${service_name}" || true
     elif which service; then
-        sudo service bind9 stop || true
+        sudo service "${service_name}" stop || true
     fi
 }
