Add support for DNS64.

diff --git a/script/_dns64 b/script/_dns64
--- a/script/_dns64
+++ b/script/_dns64
@@ -27,31 +27,52 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 #   Description:
-#       This script starts all border router services.
+#       This script manipulates dns64 configuration.
 #
 
-. "$(dirname "$0")"/_initrc
-. script/_nat64
-. script/_dns64
+BIND_CONF_OPTIONS=/etc/bind/named.conf.options
+RESOLV_CONF=/etc/resolv.conf
+NAT64_PREFIX=64:ff9b::/96
 
-main()
+DNS64_NAMESERVER_ADDR=127.0.0.1
+DNS64_CONF="dns64 `echo $NAT64_PREFIX | tr \"/\" \"\/\"` { clients { any; }; recursive-only yes; };"
+
+dns64_install()
 {
-    . $BEFORE_HOOK
-    sudo sysctl --system
-    nat64_start || die 'Failed to start NAT64!'
-    dns64_start || die 'Failed to start DNS64!'
-    if have systemctl; then
-        systemctl is-active wpantund || sudo systemctl start wpantund || die 'Failed to start wpantund!'
-        systemctl is-active otbr-web || sudo systemctl start otbr-web || die 'Failed to start otbr-web!'
-        systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'
-    elif which service; then
-        sudo service wpantund start  || die 'Failed to start wpantund!'
-        sudo service otbr-web start || die 'Failed to start otbr-web!'
-        sudo service otbr-agent start || die 'Failed to start otbr-agent!'
-    else
-        die 'Unable to find service manager. Try script/console to start in console mode!'
-    fi
-    . $AFTER_HOOK
+    with NAT64 && with DNS64 || return 0
+
+    test -f $BIND_CONF_OPTIONS || die 'Cannot find bind9 configuration file!'
+    sudo sed -i '/^};/i\\tallow-recursion { any; };' $BIND_CONF_OPTIONS
+    sudo sed -i '/^};/i\\t'"$DNS64_CONF" $BIND_CONF_OPTIONS
 }
 
-main
+dns64_uninstall()
+{
+    with NAT64 && with DNS64 || return 0
+
+    dns64_stop    
+    sudo sed -i '/^\tallow-recursion/d' $BIND_CONF_OPTIONS
+    sudo sed -i '/^\tdns64/d' $BIND_CONF_OPTIONS
+}
+
+dns64_start()
+{
+    with NAT64 && with DNS64 || return 0
+
+    if have systemctl; then    
+        sudo systemctl start bind9 || die 'Failed to start bind9!'
+    fi
+
+    sudo sed -i '1a nameserver '$DNS64_NAMESERVER_ADDR $RESOLV_CONF
+}
+
+dns64_stop()
+{
+    with NAT64 && with DNS64 || return 0
+
+    if have systemctl; then
+        sudo systemctl stop bind9 || true
+    fi
+
+    sudo sed -i '/^nameserver\s'$DNS64_NAMESERVER_ADDR'/d' $RESOLV_CONF
+}
