Implement forward safeguard

diff --git a/script/_forward_safeguard b/script/_forward_safeguard
--- a/script/_forward_safeguard
+++ b/script/_forward_safeguard
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2021, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -26,51 +26,47 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
-#   Description:
-#       This script builds and installs border router and dependencies.
-#
 
-# shellcheck source=script/_initrc
-. "$(dirname "$0")"/_initrc
-. script/_border_routing
-. script/_otbr
-. script/_ipforward
-. script/_nat64
-. script/_dns64
-. script/_dhcpv6_pd
-. script/_network_manager
-. script/_rt_tables
-. script/_swapfile
-. script/_sudo_extend
-. script/_disable_services
-. script/_forward_safeguard
+FORWARD_SAFEGUARD_SERVICE=/etc/init.d/otbr-forward-safeguard
 
-main()
+sudo modprobe ip6table_filter || true
+
+forward_safeguard_uninstall()
 {
-    . "$BEFORE_HOOK"
-    extend_sudo_timeout
-    setup_swapfile
-    disable_services
-    otbr_uninstall
-    border_routing_uninstall
-    network_manager_uninstall
-    dhcpv6_pd_uninstall
-    nat64_uninstall
-    dns64_uninstall
-    rt_tables_uninstall
-    ipforward_uninstall
-    forward_safeguard_uninstall
-
-    forward_safeguard_install
-    ipforward_install
-    rt_tables_install
-    nat64_install
-    dns64_install
-    network_manager_install
-    dhcpv6_pd_install
-    border_routing_install
-    otbr_install
-    . "$AFTER_HOOK"
+    if have systemctl; then
+        sudo systemctl disable otbr-forward-safeguard || true
+    fi
+    # systemctl disable doesn't remove sym-links
+    if have update-rc.d; then
+        sudo update-rc.d otbr-forward-safeguard remove || true
+    fi
+    test ! -f $FORWARD_SAFEGUARD_SERVICE || sudo rm $FORWARD_SAFEGUARD_SERVICE
 }
 
-main
+forward_safeguard_install()
+{
+    sudo cp script/otbr-forward-safeguard $FORWARD_SAFEGUARD_SERVICE
+    sudo chmod a+x $FORWARD_SAFEGUARD_SERVICE
+    if have systemctl; then
+        sudo systemctl enable otbr-forward-safeguard || die 'Unable to enable forward safeguard service!'
+        sudo systemctl start otbr-forward-safeguard || die 'Unable to start forward safeguard service!'
+    fi
+}
+
+forward_safeguard_start()
+{
+    if with DOCKER; then
+        service otbr-forward-safeguard start || die 'Failed to start forward safeguard'
+    elif have systemctl; then
+        sudo systemctl start otbr-forward-safeguard || die 'Failed to start forward safeguard'
+    fi
+}
+
+forward_safeguard_stop()
+{
+    if with DOCKER; then
+        service otbr-forward-safeguard stop || true
+    elif have systemctl; then
+        sudo systemctl stop otbr-forward-safeguard || true
+    fi
+}
