Add support for Beagle Bone Black as BR Platform (#115)

diff --git a/script/_initrc b/script/_initrc
--- a/script/_initrc
+++ b/script/_initrc
@@ -28,7 +28,17 @@
 #
 
 set -e
-cd "$(dirname "$0")/.."
+_HERE=$(dirname "$0")
+cd "${_HERE}/.."
+
+_checkfile=`pwd`/src/agent/main.cpp
+if [ ! -f $_checkfile ]
+then
+    echo ""
+    echo "ERROR: Cannot find checkfile: ${_checkfile}"
+    echo ""
+    exit 1
+fi
 
 die()
 {
@@ -80,6 +90,19 @@ without()
 
 # Platform information is needed to load hooks and default settings.
 #
+#----
+# BeagleBone Black debian distribution does not support "lsb_release"
+if [ -f /sys/firmware/devicetree/base/model ]
+then
+    # Note: 'model' is a binary file with no newline
+    cat /sys/firmware/devicetree/base/model | grep -s "BeagleBone Black" > /dev/null
+    if [ $? -eq 0 ]
+    then
+        PLATFORM=beagleboneblack
+    fi
+fi
+
+
 if test -z "$PLATFORM"; then
     have_or_die lsb_release
     PLATFORM=$(lsb_release -i | cut -c17- | tr '[:upper:]' '[:lower:]')
