Add error information in scripts (#56)

diff --git a/script/_ipforward b/script/_ipforward
--- a/script/_ipforward
+++ b/script/_ipforward
@@ -42,11 +42,11 @@ EOF
 
 ipforward_uninstall()
 {
-    test ! -f $SYSCTL_IP_FORWARD || sudo rm $SYSCTL_IP_FORWARD
+    test ! -f $SYSCTL_IP_FORWARD || sudo rm -v $SYSCTL_IP_FORWARD
 }
 
 ipforward_enable()
 {
-    echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/forwarding
-    echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
+    echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/forwarding || die 'Failed to enable IPv6 forwarding!'
+    echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward || die 'Failed to enable IPv4 forwarding!'
 }
diff --git a/script/_otbr b/script/_otbr
--- a/script/_otbr
+++ b/script/_otbr
@@ -52,11 +52,11 @@ otbr_install()
     if which systemctl; then
         sudo systemctl daemon-reload
         sudo systemctl enable wpantund otbr-web otbr-agent || true
-        sudo systemctl is-enabled wpantund
-        sudo systemctl is-enabled otbr-agent
-        sudo systemctl is-enabled otbr-web
+        sudo systemctl is-enabled wpantund || die 'Failed to enable wpantund!'
+        sudo systemctl is-enabled otbr-agent || die 'Failed to enable otbr-agent!'
+        sudo systemctl is-enabled otbr-web || die 'Failed to enable otbr-web!'
     else
-        >&2 echo 'WARNING: systemctl not found. otbr cannot start on boot.'
+        >&2 echo ' *** WARNING: systemctl not found. otbr cannot start on boot.'
     fi
 }
 
