Add error information in scripts

diff --git a/script/_nat64 b/script/_nat64
--- a/script/_nat64
+++ b/script/_nat64
@@ -38,6 +38,7 @@ WLAN_IFNAMES=eth0
 
 nat64_install()
 {
+    test -f $TAYGA_DEFAULT -a -f $TAYGA_CONF || die 'Cannot find tayga configuration file!'
     sudo sed -i 's/^RUN="no"/RUN="yes"/' $TAYGA_DEFAULT
     sudo sed -i 's/^prefix /##prefix /' $TAYGA_CONF
     sudo sed -i 's/^# prefix 64:ff9b::\/96/prefix 64:ff9b::\/96/' $TAYGA_CONF
@@ -110,8 +111,8 @@ esac
 EOF
     sudo chmod a+x $NAT44_SERVICE
     if which systemctl; then
-        sudo systemctl stop tayga
-        sudo systemctl enable otbr-nat44
+        sudo systemctl stop tayga || die 'Unable to stop tayga service!'
+        sudo systemctl enable otbr-nat44 || die 'Unable to enable nat44 service!'
     fi
 }
 
@@ -124,12 +125,12 @@ nat64_uninstall()
     sudo sed -i '/^ipv6-addr '$TAYGA_IPV6_ADDR'/d' $TAYGA_CONF
 
     if which systemctl; then
-        sudo systemctl disable otbr-nat44
+        sudo systemctl disable otbr-nat44 || true
     fi
 
     # systemctl disable doesn't remove sym-links
     if which update-rc.d; then
-        sudo update-rc.d otbr-nat44 remove
+        sudo update-rc.d otbr-nat44 remove || true
     fi
     test ! -f $NAT44_SERVICE || sudo rm $NAT44_SERVICE
 }
@@ -137,8 +138,8 @@ nat64_uninstall()
 nat64_start()
 {
     if which systemctl; then
-        sudo systemctl start tayga
-        sudo systemctl start otbr-nat44
+        sudo systemctl start tayga || die 'Failed to start tayga!'
+        sudo systemctl start otbr-nat44 || die 'Failed to start NAT44!'
     fi
 }
 
diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -60,7 +60,7 @@ install_packages_apt()
     sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-system-dev
 
     # nat64
-    sudo apt-get install -y tayga
+    sudo apt-get install -y tayga iptables
 }
 
 install_packages_opkg()
@@ -101,10 +101,12 @@ install_packages()
 install_uncrustify()
 {
     if test "$(uncrustify --version)" = 'uncrustify 0.64'; then
+        echo 'uncrustify-0.64 already installed'
         return
     fi
 
     BUILD_DIR=/tmp/build-$(date +%s)
+    test ! -e $BUILD_DIR || die "$BUILD_DIR already exists!"
     mkdir -p $BUILD_DIR
     (cd $BUILD_DIR &&
         wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.64.tar.gz &&
@@ -114,16 +116,18 @@ install_uncrustify()
         cd build &&
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .. &&
         make && make install DESTDIR=$STAGE_DIR &&
-        uncrustify --version)
+        uncrustify --version) || die 'Failed to build uncrustify!'
 }
 
 install_cpputest()
 {
     if test -f $STAGE_DIR/usr/lib/libCppUTest.a; then
+        echo 'CppUTest already installed'
         return
     fi
 
     BUILD_DIR=/tmp/build-$(date +%s)
+    test ! -e $BUILD_DIR || die "$BUILD_DIR already exists!"
     mkdir -p $BUILD_DIR
     (cd $BUILD_DIR &&
         wget https://github.com/cpputest/cpputest/archive/v3.8.tar.gz &&
@@ -131,7 +135,7 @@ install_cpputest()
         cd cpputest-3.8 &&
         ./autogen.sh &&
         ./configure --prefix=/usr &&
-        make install DESTDIR=$STAGE_DIR)
+        make install DESTDIR=$STAGE_DIR) || die 'Failed to build CppUTest!'
 }
 
 main()
diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -36,7 +36,7 @@ main()
 {
     . $BEFORE_HOOK
     # IPv6 is disabled by default on travis-ci
-    echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
+    echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6 || die 'Failed to enable IPv6!'
     script/test
     . $AFTER_HOOK
 }
diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -36,16 +36,12 @@
 main()
 {
     . $BEFORE_HOOK
-    if which systemctl; then
-        sudo sysctl --system
-        nat64_start
-        systemctl is-active wpantund || sudo systemctl start wpantund
-        systemctl is-active otbr-web || sudo systemctl start otbr-web
-        systemctl is-active otbr-agent || sudo systemctl start otbr-agent
-    else
-        >&2 echo 'WARNING: systemctl not found. try script/console to start in console mode.'
-        exit 1
-    fi
+    which systemctl || die 'Cannot find systemctl. Try script/console to start in console mode!'
+    sudo sysctl --system
+    nat64_start || die 'Failed to start NAT64!'
+    systemctl is-active wpantund || sudo systemctl start wpantund || die 'Failed to start wpantund!'
+    systemctl is-active otbr-web || sudo systemctl start otbr-web || die 'Failed to start otbr-web!'
+    systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'
     . $AFTER_HOOK
 }
 
