replace otbr-web

diff --git a/script/_nginx_server_install b/script/_nginx_server_install
--- a/script/_nginx_server_install
+++ b/script/_nginx_server_install
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  Copyright (c) 2017, The OpenThread Authors.
+#  Copyright (c) 2020, The OpenThread Authors.
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -26,44 +26,25 @@
 #  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #  POSSIBILITY OF SUCH DAMAGE.
 #
-#   Description:
-#       This script starts all border router services in console mode.
-#
 
-# shellcheck source=script/_initrc
-. "$(dirname "$0")"/_initrc
-# shellcheck source=script/_ipforward
-. script/_ipforward
-
-readonly TUN="${TUN:-wpan0}"
-readonly RADIO_URL="${RADIO_URL:-spinel+hdlc+uart:///dev/ttyUSB0}"
-
-killall_services()
+nginx_server_install()
 {
-    echo 'Closing services...'
-    sudo killall otbr-agent || true
-}
+    if command -v nginx; then
 
-on_exit()
-{
-    killall_services
-    . "$AFTER_HOOK"
-}
+        top_dir="$(pwd)"
 
-main()
-{
-    . "$BEFORE_HOOK"
-    if have systemctl; then
-        sudo systemctl stop otbr-agent || true
+        nginx_conf_file=$(nginx -V 2>&1 | grep -o "\-\-conf-path=\(.*conf\)" | cut -d "=" -f2)
+
+        sudo rm "${nginx_conf_file}"
+
+        sudo cp "${top_dir}"/etc/rest/nginx.conf "${nginx_conf_file}"
+
+        sudo sed -i.bak "s:to be set:${top_dir}/src/rest/frontend:" "${nginx_conf_file}"
+
+    else
+
+        echo >&2 ' *** WARNING: nginx not found, please install nginx manually and run setup again'
+
     fi
-    killall_services
 
-    trap on_exit INT TERM EXIT
-    ipforward_enable
-    sudo sh -s <<EOF
-otbr-agent -I $TUN "${RADIO_URL}" &
-wait
-EOF
 }
-
-main
