update for comments

diff --git a/script/cmake-build b/script/cmake-build
--- a/script/cmake-build
+++ b/script/cmake-build
@@ -40,15 +40,15 @@
 #
 #  Compile with the specified ninja build target:
 #
-#      OTBR_CMAKE_NINJA_TARGET="${target}" script/cmake-build
+#      TARGET="${target}" script/cmake-build
 #
 #  Compile with the specified build directory:
 #
-#      OTBR_CMAKE_BUILD_DIR="./build/temp" script/cmake-build
+#      BUILD_DIR="./build/temp" script/cmake-build
 #
 #  Compile and install the build target:
 #
-#      OTBR_CMAKE_NINJA_INSTALL=ON script/cmake-build
+#      INSTALL=1 script/cmake-build
 #
 #  Examples:
 #
@@ -56,7 +56,7 @@
 #
 #      script/cmake-build -DOTBR_DBUS=ON
 #
-#      OTBR_CMAKE_BUILD_DIR="./build/temp" OTBR_CMAKE_NINJA_TARGET="otbr-agent" OTBR_CMAKE_NINJA_INSTALL=ON script/cmake-build -DOTBR_DBUS=ON
+#      BUILD_DIR="./build/temp" TARGET="otbr-agent" INSTALL=1 script/cmake-build -DOTBR_DBUS=ON
 #
 
 # shellcheck source=script/_initrc
@@ -65,29 +65,30 @@
 readonly OTBR_TOP_SRCDIR="$PWD"
 readonly OTBR_TOP_BUILD_DIR="${BUILD_DIR}/otbr"
 
-OTBR_CMAKE_NINJA_TARGET=${OTBR_CMAKE_NINJA_TARGET:-}
-OTBR_CMAKE_NINJA_INSTALL=${OTBR_CMAKE_NINJA_INSTALL:-}
+TARGET=${TARGET:-}
+INSTALL=${INSTALL:-}
 
 main()
 {
-    local builddir="${OTBR_CMAKE_BUILD_DIR:-${OTBR_TOP_BUILD_DIR}}"
+    local builddir="${BUILD_DIR:-${OTBR_TOP_BUILD_DIR}}"
 
     mkdir -p "${builddir}"
-    cd "${builddir}" || die "Failed to enter ${builddir}"
 
-    cmake -GNinja "${OTBR_TOP_SRCDIR}" "$@"
+    (
+        cd "${builddir}" || die "Failed to enter ${builddir}"
 
-    if [[ -n ${OTBR_CMAKE_NINJA_TARGET[*]} ]]; then
-        ninja "${OTBR_CMAKE_NINJA_TARGET[@]}"
-    else
-        ninja
-    fi
+        cmake -GNinja "${OTBR_TOP_SRCDIR}" "$@"
 
-    if [[ ${OTBR_CMAKE_NINJA_INSTALL} == "ON" ]]; then
-        sudo ninja install
-    fi
+        if [[ -n ${TARGET[*]} ]]; then
+            ninja "${TARGET[@]}"
+        else
+            ninja
+        fi
 
-    cd "${OTBR_TOP_SRCDIR}" || die "Failed to enter ${OTBR_TOP_SRCDIR}"
+        if [[ ${INSTALL} == "1" ]]; then
+            sudo ninja install
+        fi
+    )
 }
 
 main "$@"
