[cmake] transition to cmake
* use cmake for building otbr-agent
* use cmake for all tests.
* use cmake for OpenWrt.
* move dbus test into check
* remove raspbian jessie test for it very hard to upgrade cmake

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #  Copyright (c) 2017, The OpenThread Authors.
 #  All rights reserved.
@@ -46,12 +46,12 @@ main()
         systemctl is-active avahi-daemon || sudo systemctl start avahi-daemon || die 'Failed to start avahi!'
         systemctl is-active otbr-web || sudo systemctl start otbr-web || die 'Failed to start otbr-web!'
         systemctl is-active otbr-agent || sudo systemctl start otbr-agent || die 'Failed to start otbr-agent!'
-    elif which service; then
+    elif have service; then
         sudo service rsyslog status || sudo service rsyslog start || die 'Failed to start rsyslog!'
         sudo service dbus status || sudo service dbus start  || die 'Failed to start dbus!'
         sudo service avahi-daemon status || sudo service avahi-daemon start  || die 'Failed to start avahi!'
-        sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'
         sudo service otbr-agent status || sudo service otbr-agent start || die 'Failed to start otbr-agent!'
+        sudo service otbr-web status || sudo service otbr-web start || die 'Failed to start otbr-web!'
     else
         die 'Unable to find service manager. Try script/console to start in console mode!'
     fi
