[tests] enhance expect test framework for ncp_mode

diff --git a/tests/scripts/ncp_mode b/tests/scripts/ncp_mode
--- a/tests/scripts/ncp_mode
+++ b/tests/scripts/ncp_mode
@@ -40,6 +40,9 @@ readonly EXPECT_SCRIPT_DIR
 #---------------------------------------
 # Configurations
 #---------------------------------------
+OT_CLI="${OT_CLI:-ot-cli-ftd}"
+readonly OT_CLI
+
 OT_NCP="${OT_NCP:-ot-ncp-ftd}"
 readonly OT_NCP
 
@@ -125,7 +128,8 @@ readonly TUN_NAME
 #----------------------------------------
 build_ot_simulation()
 {
-    "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_APP_CLI=OFF -DOT_MTD=OFF
+    "${ABS_TOP_OT_SRCDIR}"/script/cmake-build simulation -DOT_MTD=OFF
+    ot_cli=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_CLI}")
     ot_ncp=$(find "${ABS_TOP_OT_BUILDDIR}" -name "${OT_NCP}")
 }
 
@@ -216,9 +220,15 @@ main()
     export EXP_OTBR_AGENT_PATH="${OTBR_AGENT_PATH}"
     export EXP_TUN_NAME="${TUN_NAME}"
     export EXP_LEADER_NODE_ID="${LEADER_NODE_ID}"
+    export EXP_OT_CLI_PATH="${ot_cli}"
     export EXP_OT_NCP_PATH="${ot_ncp}"
-    otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_version.exp" || die "ncp expect script failed!"
-    otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_get_device_role.exp" || die "ncp expect script failed!"
+
+    if [[ $# != 0 ]]; then
+        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/$1" || die "ncp expect script failed!"
+    else
+        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_version.exp" || die "ncp expect script failed!"
+        otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_get_device_role.exp" || die "ncp expect script failed!"
+    fi
 }
 
 main "$@"
