[ncp] implement dbus server for NCP mode (#2339)
This commit refactors the `DBusAgent` so that it can work under NCP
mode.

The DBus server will provide different methods under RCP mode and NCP
mode. Currently under NCP mode, only `GetDeviceRole` is provided.

This commit renames `DBusThreadObject` to `DBusThreadObjectRcp` and
added a new class `DBusThreadObjectNcp` which will handle the DBus
requests under NCP mode. This PR also implements
`AsyncPropertyHandler` to handle GetProperty requests by calling async
methods of `NcpHost`.

A test case is added to test `GetDeviceRole` under NCP.

diff --git a/tests/scripts/ncp_mode b/tests/scripts/ncp_mode
--- a/tests/scripts/ncp_mode
+++ b/tests/scripts/ncp_mode
@@ -218,6 +218,7 @@ main()
     export EXP_LEADER_NODE_ID="${LEADER_NODE_ID}"
     export EXP_OT_NCP_PATH="${ot_ncp}"
     otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_version.exp" || die "ncp expect script failed!"
+    otbr_exec_expect_script "${EXPECT_SCRIPT_DIR}/ncp_get_device_role.exp" || die "ncp expect script failed!"
 }
 
 main "$@"
